version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    depends_on:
      - django_docker

    restart: "always"

  django_docker:
    build: ./
    command: sh -c "gunicorn django_docker.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000

    restart: "always"